name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.20.1
  - jupyter=1.0.0
  - xarray=0.19.0
  - netCDF4=1.5.7
  - Bottleneck=1.3.2
  - dask=2021.9.1
  - climlab=0.7.12
  - pip
  - python=3.9.7
  - pip:
    - setuptools==56.0.0
    - pyleoclim==0.7.0
