name: pyleoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cartopy=0.18.0
  - certifi=2020.12.5
  - cftime=1.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - freetype=2.10.4
  - geos=3.8.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - intel-openmp=2019.4
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - lz4-c=1.9.3
  - matplotlib-base=3.3.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random
  - ncurses=6.2
  - netcdf4=1.5.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pillow=8.1.0
  - pip=20.3.3
  - proj=7.2.0
  - pyparsing=2.4.7
  - pyshp=2.1.3
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - readline=8.0
  - scipy=1.5.2
  - setuptools=51.3.3
  - shapely=1.7.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bagit==1.7.0
    - bleach==3.2.1
    - cffi==1.14.4
    - chardet==4.0.0
    - cython==0.29.21
    - decorator==4.4.2
    - defusedxml==0.6.0
    - demjson==2.2.4
    - dill==0.3.3
    - entrypoints==0.3
    - idna==2.10
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - lipd==0.2.8.5
    - llvmlite==0.35.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - multiprocess==0.70.11.1
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.4.3
    - networkx==2.5
    - nibabel==3.2.1
    - nitime==0.9
    - notebook==6.2.0
    - numba==0.52.0
    - packaging==20.8
    - pandas==1.2.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pathos==0.2.7
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pox==0.2.9
    - ppft==1.6.6.3
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.10
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.7.4
    - pyhht==0.1.0
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyrsistent==0.17.3
    - pytz==2020.5
    - pywavelets==1.1.1
    - pyzmq==21.0.1
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - requests==2.25.1
    - scikit-learn==0.24.1
    - seaborn==0.11.1
    - send2trash==1.5.0
    - sip==6.0.0
    - statsmodels==0.12.1
    - tabulate==0.8.7
    - testpath==0.4.4
    - tftb==0.1.1
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - tqdm==4.56.0
    - traitlets==5.0.5
    - unidecode==1.1.2
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - wget==3.2
    - widgetsnbextension==3.5.1
    - xarray==0.16.2
    - xlrd==2.0.1
    - climlab
    - pyleoclim
    - nbgitpuller==0.9.0


