name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.20.1
  - jupyter=1.0.0
  - xarray=0.19.0
  - climlab=0.7.12
  - pip
  - pip:
    - lipd==0.2.8.7
    - demjson==2.2.4
    - pyleoclim==0.6.3b0
