name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.20.1
  - jupyter=1.0.0
  - xarray=0.19.0
  - climlab=0.7.12
  - pip
  - python=3.9.7
  - pip:
    - git+https://github.com/LinkedEarth/Pyleoclim_util.git@Development
